### ISSUE TITLE
How can I use typescript template for react?

### ISSUE THREAD

**Issue by huykon** [github/codespaces-react#18]
How can I use typescript template for react?

**Comment by BigDaddylyons** [comment]
Can you help me out on my website

**Comment by joshaber** [comment]
@huykon We don't have a TypeScript + React template currently but we'll keep it in mind for the future!

**Comment by huykon** [comment]
let me know when this supported react typescript template @joshaber

**Comment by BigDaddylyons** [comment]
money for me
